#!/bin/sh
# -*- mode: shell-script -*-

SCRIPTNAME=$(basename $0)
BASEDIR=${BASEDIR:-"$(dirname $(realpath $0))"}
SUPPORTDIR=${SUPPORTDIR:-"$(dirname $(dirname $BASEDIR))/support"}

LOGFILE=${LOGFILE:-"$0.log"}
PRODSITE=prod
DEVSITE=dev

PRODBRANCH=master
DEVBRANCH=dev
# PRODBRANCH=test-ignore
# DEVBRANCH=test-ignore

URLTEMPLATE='http://%slincs.hms.harvard.edu/cgi-bin/cleanup.cgi'

ORIGIN=${ORIGIN:-git@github.com:hmslincs/hmslincs.git}
FULL=false
STATICS=true

function error {
  echo "$SCRIPTNAME: $1" >&2
  exit 1
}

function __usage {
    echo "$SCRIPTNAME [-h|-m|-f] [SITE [BRANCH]]"
    echo "  -h -- this help message"
    echo "  -m -- minimal update"
    echo "  -f -- do full update (rebuild db, remake and move images, etc.)"
    echo
    echo "SITE should be either $PRODSITE or $DEVSITE.  BRANCH should be a suitable "
    echo "branch from $ORIGIN."
    echo
    echo "Default actions: git-pull, make and move files, kill fast cgi."
}

function main {
  OPTIND=1
  while getopts ":hmf" opt "$@"
  do
    case "$opt" in
      h)  __usage
          return 0;;
      m) FULL=false
         STATICS=false;;
      f) FULL=true
         STATICS=true;;
      ?) echo "Invalid option: -$OPTARG" >&2
         __usage
         return 1;;
    esac
  done

  shift $(( OPTIND - 1 ))

  cd "$BASEDIR" || error "can't cd to $BASEDIR"

  SITE="$1"
  BRANCH="$2"

  if [ -z "$SITE" ]; then
    case "$BASEDIR" in
      /www/lincs.*) SITE="$PRODSITE" ;;
      *) SITE="$DEVSITE" ;;
    esac
  fi

  if [ -z "$BRANCH" ]; then
    if [ "$SITE" = "$PRODSITE" ]; then
      BRANCH="$PRODBRANCH"
    else
      BRANCH="$DEVBRANCH"
    fi
  fi

  local urlprefix
  if [ "$SITE" = "$PRODSITE" ]; then
    urlprefix=""
  else
    urlprefix="dev."
  fi

  URL=$(printf "$URLTEMPLATE" "$urlprefix")

  if $DEBUG; then
    echo
    echo 'params:'
    echo "SITE: $SITE"
    echo "ORIGIN: $ORIGIN"
    echo "BRANCH: $BRANCH"
    echo "URL: $URL"
    echo
  fi

  deploy || error "failed with status $?"

  return 0
}

function gitpull {
  $DEBUG && echo -n "pulling branch $BRANCH from $ORIGIN... "
  git checkout $BRANCH >>"$LOGFILE" 2>&1 || error "git-checkout failed: $?"
  git pull $ORIGIN $BRANCH: >>"$LOGFILE" 2>&1 || error "git-pull failed: $?"

  # local lastline
  # lastline=$(tail -1 "$LOGFILE")
  # [ "$lastline" = 'Already up-to-date.' ] && return 1
  # echo "stayed: $lastline"

  $DEBUG && echo 'done'
  return 0
}

function builddb {
  if $FULL; then
    $DEBUG && echo -n 'building db... '
    $BASEDIR/re_run.sh $SITE >>"$LOGFILE" 2>&1 || error "re_run.sh failed: $?"
    $DEBUG && echo 'done'
  fi
}

function makeimg {
  if $STATICS; then
    $DEBUG && echo -n 'making images... '
    cd "$BASEDIR" || return 1
    src/do_scatterplots.sh >>"$LOGFILE" 2>&1 || \
        error "src/do_scatterplots.sh failed: $?"
    $DEBUG && echo 'done'
  fi
}

function moveimg {
  if $STATICS; then
    $DEBUG && echo -n 'moving images... '
    cd "$BASEDIR" || return 1
    ./find_and_move_restricted_images.sh >>"$LOGFILE" 2>&1 || \
        error "find_and_move_restricted_images.sh failed: $?"
    $DEBUG && echo 'done'
  fi
}

function collectstatic {
  if $STATICS; then
    $DEBUG && echo -n 'collecting statics... '
    cd "$BASEDIR" || return 1
    mkdir -p $SUPPORTDIR/images || return 1
    python django/manage.py collectstatic --noinput >>"$LOGFILE" 2>&1 || \
        error "manage.py collectstatic failed: $?"
    $DEBUG && echo 'done'
  fi
}

function killfcgi {
  $DEBUG && echo -n 'running cleanup.cgi... '
  curl -sf "$URL" >> "$LOGFILE" || error '"'"curl -f $URL"'" failed'
  $DEBUG && echo 'done'
}

function deploy {
  date +'%n%c' >>"$LOGFILE"
  gitpull && builddb && makeimg && moveimg && collectstatic && killfcgi
  echo done
}

main $@
